"""Initial schema

Revision ID: b2a527e102d4
Revises: 
Create Date: 2026-08-17 02:19:47.371849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2a527e102d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_token_blocklist_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email_lower', [sa.text('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
        batch_op.create_index('ix_users_username_lower', [sa.text('lower(username)')], unique=True)

    op.create_table('admin_audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_target_id'), ['target_id'], unique=False)

    op.create_table('bill_definitions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recurrence', sa.Enum('NONE', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurrence_type'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='bill_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_definitions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_bill_definitions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_email_verification_tokens_user_id', ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('REVIEW', 'BUG', 'IMPROVEMENT', 'FEATURE_REQUEST', 'OTHER', name='feedback_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWING', 'PLANNED', 'RESOLVED', 'DISMISSED', name='feedback_status'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_feedback_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_password_reset_tokens_user_id', ['user_id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('reminder_7_days', sa.Boolean(), nullable=False),
    sa.Column('reminder_3_days', sa.Boolean(), nullable=False),
    sa.Column('reminder_1_day', sa.Boolean(), nullable=False),
    sa.Column('reminder_due_today', sa.Boolean(), nullable=False),
    sa.Column('overdue_reminders', sa.Boolean(), nullable=False),
    sa.Column('private_notification_text', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bill_occurrences',
    sa.Column('bill_definition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_definition_id'], ['bill_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_definition_id', 'due_date', name='uq_bill_occurrence_def_due_date')
    )
    with op.batch_alter_table('bill_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_occurrences_bill_definition_id'), ['bill_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_occurrences_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_occurrences_is_paid'), ['is_paid'], unique=False)
        batch_op.create_index('ix_bill_occurrences_user_due', ['user_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_occurrences_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_bill_occurrences_user_paid', ['user_id', 'is_paid'], unique=False)

    op.create_table('bill_documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bill_definition_id', sa.UUID(), nullable=True),
    sa.Column('bill_occurrence_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_definition_id'], ['bill_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bill_occurrence_id'], ['bill_occurrences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('bill_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_documents_bill_definition_id'), ['bill_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_documents_bill_occurrence_id'), ['bill_occurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_documents_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bill_occurrence_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('REMINDER_7_DAY', 'REMINDER_3_DAY', 'REMINDER_1_DAY', 'REMINDER_DUE_TODAY', 'REMINDER_OVERDUE_1', 'REMINDER_OVERDUE_2', 'REMINDER_OVERDUE_3', name='notification_type'), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'EMAIL', name='notification_channel'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_occurrence_id'], ['bill_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_occurrence_id', 'type', 'channel', name='uq_notification_occurrence_type_channel')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_bill_occurrence_id'), ['bill_occurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bill_occurrence_id', sa.UUID(), nullable=False),
    sa.Column('bill_definition_id', sa.UUID(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bill_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_definition_id'], ['bill_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bill_occurrence_id'], ['bill_occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_bill_definition_id'), ['bill_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_bill_occurrence_id'), ['bill_occurrence_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index('ix_payments_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_payments_user_paid_at', ['user_id', 'paid_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_user_paid_at')
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index('ix_payments_user_category')
        batch_op.drop_index(batch_op.f('ix_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payments_bill_occurrence_id'))
        batch_op.drop_index(batch_op.f('ix_payments_bill_definition_id'))

    op.drop_table('payments')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_bill_occurrence_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('bill_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_bill_documents_bill_occurrence_id'))
        batch_op.drop_index(batch_op.f('ix_bill_documents_bill_definition_id'))

    op.drop_table('bill_documents')
    with op.batch_alter_table('bill_occurrences', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_occurrences_user_paid')
        batch_op.drop_index(batch_op.f('ix_bill_occurrences_user_id'))
        batch_op.drop_index('ix_bill_occurrences_user_due')
        batch_op.drop_index(batch_op.f('ix_bill_occurrences_is_paid'))
        batch_op.drop_index(batch_op.f('ix_bill_occurrences_due_date'))
        batch_op.drop_index(batch_op.f('ix_bill_occurrences_bill_definition_id'))

    op.drop_table('bill_occurrences')
    op.drop_table('user_settings')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_password_reset_tokens_user_id')

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_status'))

    op.drop_table('feedback')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_email_verification_tokens_user_id')

    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('bill_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_definitions_user_status')
        batch_op.drop_index(batch_op.f('ix_bill_definitions_user_id'))

    op.drop_table('bill_definitions')
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_actor_user_id'))

    op.drop_table('admin_audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username_lower')
        batch_op.drop_index('ix_users_email_lower', postgresql_where=sa.text('email IS NOT NULL'))

    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
